name: sample

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload an artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: test/**

  release: 
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download an artifact
      uses: actions/download-artifact@v3
    
    - name: Display structure of downloaded files
      run: ls -R